source 'https://rubygems.org'

ruby '2.1.4'
gem 'rerun'
gem 'sinatra'
gem 'unicorn'
gem 'carrierwave'
gem 'mini_magick'
gem 'clockwork'
gem 'jbuilder'
gem 'haml'
gem 'feedjira'
gem 'grape'
gem 'rake'
gem 'rack-test'
gem 'sass'
gem 'factory_girl'

gem 'mongoid'
gem 'mongoid_auto_increment_id'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'delayed_job_mongoid'

gem 'pry'
gem 'minitest'
gem 'database_cleaner'
